### ISSUE TITLE
Segmentation effect active after leaving Editor

### ISSUE THREAD

**Issue by fedorov** [QIICR/PET-IndiC#4]
It would be good to disable the effect when user leaves the module

**Comment by pieper** [comment]
See:

https://github.com/Slicer/Slicer/blob/846a654748e263ca51ac43c0d324d260c03e008e/Modules/Scripted/Editor/Editor.py#L166-L176

**Comment by chribaue** [comment]
I fixed this issue.

**Comment by fedorov** [comment]
👍
