### ISSUE TITLE
Remove dependency on deprecated Slicer core modules

### ISSUE THREAD

**Issue by lassoan** [QIICR/PET-IndiC#6]
We are planning to remove Slicer core modules that have been superseded by other modules.
https://discourse.slicer.org/t/removing-legacy-modules-in-slicer5/11371

We have noticed that this extension currently uses legacy editor module, instead of the current Segment Editor module.

If you want your extension to be available for the upcoming Slicer5 release, please remove dependency to deprecated modules. If you have any questions or need any help with the upgrade, you can write here or post to the Slicer forum. Thank you for your contribution.

**Comment by chribaue** [comment]
Hi Andras,

two months go someone from the Slicer Core team mentioned that the "Legacy Editor" Module will get moved to a separate, but unmaintained Extension that can get installed via the Extension Manager. I think that's a great idea! The Slicer core team does not have to maintain it any longer as part of the Slicer core. But extensions that use it still remain their functionality for a while longer by just installing this extra "Legacy Editor" extension. It would also make life easier for a few Extension maintainers who don't have the funds to refactor their code to work with the newer infrastructure.

In our case we have some of tutorial videos etc. online and some users out there who still want to use the functionality via the legacy editor.

I hope you still plan to create this "Legacy Editor" extension. Please let me know.

**Comment by lassoan** [comment]
The legacy Editor will remain available in Slicer4, so there is no need for immediate action on your side.

It would take several days of work to move the legacy Editor out to a separate extension in Slicer5 and some more time to make sure it remains functional. Since it is much less work to upgrade a module to use Segment Editor instead, we would only consider this option if there are many extensions that would opt for this short-term workaround (this does not look very likely for now).

We spend a lot of time adjusting our software to changing APIs of various libraries, so I know how frustrating this is. We try to remain backward compatible as long as possible and only make API changes if there are significant benefits. We have been keeping legacy Editor around for about 4 years and switching to Segment Editor has many substantial advantages (for both users and developers).

We can help you upgrading your module, just let us know if you have any specific questions or issues. We can also add features to the Segment Editor if you cannot easily reproduce some behavior of the legacy Editor.

**Comment by chribaue** [comment]
Our Extension consists of 3 modules:
  * A CLI to calculate quantitative PET Indices
  * A Segment Statistics Plugin, which allows using it
  * A GUI module to segment lesions using the legacy editor and to calculate quantitative Indices on the fly as the segmentation changes.

The first two will remain fully functional. For the GUI module the QuantitativeReporting Extension works as a replacement using the newer Segment Editor with much more functionality. It's just that some user's liked the PET IndiC GUI module for its simplicity. And all our tutorial videos use it, which I think we will not be able to redo.

I saw in another thread that you plan for a Slicer 4.12, before removing any functionality. I also support this idea. At least we can refer to a "recent" version where everything is working.

**Comment by lassoan** [comment]
> It's just that some user's liked the PET IndiC GUI module for its simplicity.

Segment Editor can be made look similar to the legacy Editor (all advanced features can be hidden, list and order of displayed effects can be customized, etc.). Also, since upgrading provides some benefits (real-time 3D display, higher-quality slice display, show/hide individual segments, etc.) they may accept the inconvenience of adapting to slight differences.

> And all our tutorial videos use it, which I think we will not be able to redo.

You don't need to redo videos. We asked users several times what they think about tutorials where GUI is slightly different from current GUI and the answer was always that it was not a problem. If you need to create new videos anyway then you'll use the new GUI and may replace the old videos, but until then the old ones should work.

> I saw in another thread that you plan for a Slicer 4.12, before removing any functionality. I also support this idea.

Can you add your comments to that discussion (https://github.com/Slicer/Slicer/pull/4904)?
